import type { Flight } from "@hewa/console-types";

/**
 * Seed flights for the console's `flights` view.
 *
 * The operator is on the record. It used to be a callsign-prefix table inside the
 * app's data module, which meant the carrier chip in the summary bar was counting
 * a value the service had never been asked about, and a new domestic prefix had to
 * be added in two places to appear in one column. Three of the flights below are
 * on carriers the prefix table never heard of, which is what "Unknown" is for.
 */
export const FLIGHTS: Flight[] = [
  {
    icao24: "4ca1d2",
    callsign: "KQ100",
    originCountry: "Kenya",
    lat: 2.184,
    lng: 35.442,
    altitude: 11582,
    velocity: 248,
    heading: 312,
    isArriving: false,
    isDeparting: false,
    carrier: "Kenya Airways",
  },
  {
    icao24: "4ca305",
    callsign: "KQ310",
    originCountry: "Kenya",
    lat: -2.874,
    lng: 38.561,
    altitude: 3048,
    velocity: 210,
    heading: 134,
    isArriving: true,
    isDeparting: false,
    carrier: "Kenya Airways",
  },
  {
    icao24: "4ca788",
    callsign: "KQ480",
    originCountry: "Kenya",
    lat: 0.412,
    lng: 34.921,
    altitude: 10973,
    velocity: 245,
    heading: 92,
    isArriving: false,
    isDeparting: false,
    carrier: "Kenya Airways",
  },
  {
    icao24: "068d1a",
    callsign: "JM8200",
    originCountry: "Kenya",
    lat: 0.884,
    lng: 34.612,
    altitude: 10668,
    velocity: 232,
    heading: 268,
    isArriving: false,
    isDeparting: false,
    carrier: "Jambojet",
  },
  {
    icao24: "068e44",
    callsign: "JM8215",
    originCountry: "Kenya",
    lat: -1.402,
    lng: 36.891,
    altitude: 2743,
    velocity: 195,
    heading: 47,
    isArriving: false,
    isDeparting: true,
    carrier: "Jambojet",
  },
  {
    icao24: "06b1c2",
    callsign: "JB3200",
    originCountry: "Kenya",
    lat: -0.877,
    lng: 36.104,
    altitude: 10363,
    velocity: 228,
    heading: 203,
    isArriving: false,
    isDeparting: false,
    carrier: "Jambojet",
  },
  {
    icao24: "048f31",
    callsign: "FY312",
    originCountry: "Kenya",
    lat: -0.238,
    lng: 35.104,
    altitude: 9144,
    velocity: 210,
    heading: 18,
    isArriving: false,
    isDeparting: false,
    carrier: "Fly540",
  },
  {
    icao24: "048e77",
    callsign: "5F401",
    originCountry: "Kenya",
    lat: -0.041,
    lng: 34.702,
    altitude: 2438,
    velocity: 180,
    heading: 176,
    isArriving: true,
    isDeparting: false,
    carrier: "Fly540",
  },
  {
    icao24: "064b90",
    callsign: "FL8110",
    originCountry: "Kenya",
    lat: 0.533,
    lng: 35.278,
    altitude: 8839,
    velocity: 215,
    heading: 224,
    isArriving: false,
    isDeparting: false,
    carrier: "Safarilink",
  },
  {
    icao24: "064c3a",
    callsign: "FLC611",
    originCountry: "Kenya",
    lat: 1.104,
    lng: 36.712,
    altitude: 3658,
    velocity: 190,
    heading: 301,
    isArriving: false,
    isDeparting: true,
    carrier: "Safarilink",
  },
  {
    icao24: "06a2f8",
    callsign: "XK621",
    originCountry: "Kenya",
    lat: -3.204,
    lng: 38.884,
    altitude: 10058,
    velocity: 240,
    heading: 161,
    isArriving: false,
    isDeparting: false,
    carrier: "Safarilink",
  },
  {
    icao24: "06a311",
    callsign: "XK450",
    originCountry: "Kenya",
    lat: -3.921,
    lng: 39.564,
    altitude: 1829,
    velocity: 175,
    heading: 21,
    isArriving: true,
    isDeparting: false,
    carrier: "Safarilink",
  },
  {
    icao24: "89640d",
    callsign: "QTR1369",
    originCountry: "Qatar",
    lat: 3.612,
    lng: 40.884,
    altitude: 11097,
    velocity: 252,
    heading: 341,
    isArriving: false,
    isDeparting: false,
    carrier: "Unknown",
  },
  {
    icao24: "800f52",
    callsign: "UGA410",
    originCountry: "Uganda",
    lat: 0.204,
    lng: 33.981,
    altitude: 10058,
    velocity: 235,
    heading: 182,
    isArriving: false,
    isDeparting: false,
    carrier: "Unknown",
  },
  {
    icao24: "70bd21",
    callsign: "ETH302",
    originCountry: "Ethiopia",
    lat: 2.884,
    lng: 39.104,
    altitude: 10973,
    velocity: 246,
    heading: 196,
    isArriving: false,
    isDeparting: false,
    carrier: "Unknown",
  },
];

/**
 * Every carrier the summary bar names.
 *
 * Hand-written, and not derived from the flights: a bar built out of the rows it
 * is counting loses a chip the moment an operator has nothing in the air, which is
 * the one moment an operator most wants to press it. "Unknown" is one of them, and
 * it is a real carrier as far as this table is concerned.
 */
export const CARRIERS = ["Kenya Airways", "Jambojet", "Fly540", "Safarilink", "Unknown"];
